"""Generate + verify the Tier-B OS-cron resume driver (`.conductor/resume-autodev.sh`).

Why this is a tested module, not skill prose: the live-run silent-stall of 2026-07-05
(docs/reviews/2026-07-05-conductor-tier-b-driver-robustness.md) traced to prose that told the
agent to "write a resume script that runs `claude -p ...`" without saying HOW to resolve the
bins under cron's minimal PATH. The agent baked in generation-time absolute paths (a
node-version-pinned `claude`, a version-pinned `conductor`); both rotted on the next
claude/plugin upgrade and every headless fire died silently. Making the script mechanical fixes
the root cause: one source of truth, resolved at RUN time, verifiable on reconcile.

Split of concerns the render enforces:
- MECHANICAL (this module owns, regenerable): bin resolution, PATH repair, fail-loud, the three
  guards (no-double-drive, done-gate-green exit, flock), the fire.
- OWNER/MACHINE config (never baked here, sourced from `<project>/.conductor/resume-env.sh` so
  regeneration can never clobber it): `CONDUCTOR_MERGE_VERIFY`, `CONDUCTOR_PLUGIN_DIRS`,
  `DOCKER_HOST`, `CONDUCTOR_RESUME_CLAUDE_FLAGS`.

`CONDUCTOR_RUN_BRANCH` is deliberately NOT exported: a stale literal would override
`.conductor/run_branch` in `merge_gate._expected_base()` and pin an out-of-date branch. The file
is the single source of truth.
"""

from __future__ import annotations

import argparse
import os
import re
import shlex
import stat
import sys

# Bump when `render` changes so `verify` flags already-installed scripts as stale and
# `/conductor:start` reconcile regenerates them (self-heal on upgrade).
TEMPLATE_VERSION = 4
_MARKER = f"# conductor-resume-template: v{TEMPLATE_VERSION}"

# Antipatterns whose PRESENCE in an installed script means it is a rotted pre-v2 driver: a
# node-version-pinned bin path, or a plugin path pinned to a specific conductor version.
_ROT_PATTERNS = (
    (
        re.compile(r"/versions/v?\d+\.\d+\.\d+/"),
        "version-pinned runtime path (rots on upgrade)",
    ),
    (
        re.compile(r"/conductor/\d+\.\d+\.\d+/bin/conductor"),
        "version-pinned conductor path (rots on upgrade)",
    ),
)
# Owner/machine env an old inline script may carry; verify surfaces these so a regeneration
# migrates them to resume-env.sh instead of silently dropping them.
_OWNER_ENV_RE = re.compile(
    r"^\s*export\s+(CONDUCTOR_MERGE_VERIFY|CONDUCTOR_PLUGIN_DIRS|DOCKER_HOST|CONDUCTOR_RESUME_CLAUDE_FLAGS)\b",
    re.MULTILINE,
)


def render(project: str, worktree: str) -> str:
    """The Tier-B driver script, deterministic in (project, worktree). project = the owner
    main-checkout root (lock + log live there, shared across drivers); worktree = the run
    worktree the worker resumes in (never the owner checkout). Paths are rendered with
    shlex.quote so a directory name containing a space/quote/`$` can't break or inject into the
    emitted shell."""
    return f"""#!/usr/bin/env bash
{_MARKER}
# conductor Tier-B resume driver — GENERATED by `conductor resume-script write`. Do NOT hand-edit.
#
# OWNER-OWNED run infrastructure: the autodev worker never modifies it. `/conductor:start`
# reconcile regenerates it (via `conductor resume-script verify` -> `write`) when this template
# changes or its bins stop resolving, so a claude/node/plugin upgrade SELF-HEALS instead of
# silently stalling. Machine/run-specific env (CONDUCTOR_MERGE_VERIFY, CONDUCTOR_PLUGIN_DIRS,
# DOCKER_HOST, CONDUCTOR_RESUME_CLAUDE_FLAGS) lives in <project>/.conductor/resume-env.sh — this
# script sources it and never bakes it in, so regeneration can never clobber owner config.
set -u

PROJECT={shlex.quote(project)}
WORKTREE={shlex.quote(worktree)}
LOG="$PROJECT/.conductor/resume-autodev.log"
ts() {{ date -Is 2>/dev/null || date; }}

# Cron gives a minimal PATH — re-add the known install roots BEFORE resolving bins.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin${{PATH:+:$PATH}}"

# Resolve bins at RUN time. NEVER pin generation-time paths: a versioned node path or a
# version-pinned plugin dir rots on the next upgrade and the fire then dies silently.
CLAUDE_BIN="$(command -v claude || true)"
[ -x "$CLAUDE_BIN" ] || CLAUDE_BIN="$HOME/.local/bin/claude"   # claude 2.x standalone launcher (stable, unversioned)
CONDUCTOR="$(command -v conductor || true)"
[ -x "$CONDUCTOR" ] || CONDUCTOR="$(ls -d "$HOME"/.claude/plugins/cache/*/conductor/*/bin/conductor 2>/dev/null | sort -V | tail -1)"

# Fail LOUD if a bin is unresolvable — silence is the real defect; a stalled run must be visible.
if [ ! -x "$CLAUDE_BIN" ] || [ ! -x "${{CONDUCTOR:-}}" ]; then
    printf '%s driver-unresolved claude=%s conductor=%s\\n' "$(ts)" "$CLAUDE_BIN" "${{CONDUCTOR:-}}" >> "$LOG"
    exit 3
fi

# Owner/machine env (merge-verify command, plugin dirs, docker host, extra claude flags). Kept
# OUT of this generated file so regeneration never clobbers it. SAFETY: the file can carry the
# bypass flag and a shell-executed CONDUCTOR_MERGE_VERIFY, so a group- or world-writable copy is
# a privilege-escalation vector — refuse it LOUD (env-unsafe, exit 5) before sourcing, like
# driver-unresolved. Only a 0600 (or absent) file proceeds to the fire.
ENV_FILE="$PROJECT/.conductor/resume-env.sh"
if [ -f "$ENV_FILE" ]; then
    ENV_MODE="$(stat -c '%a' "$ENV_FILE" 2>/dev/null || stat -f '%Lp' "$ENV_FILE" 2>/dev/null)"
    # FAIL-CLOSED: an unreadable mode (both stat forms failed) refuses like a writable one.
    if [ -z "$ENV_MODE" ] || [ $(( 8#$ENV_MODE & 8#022 )) -ne 0 ]; then
        printf '%s env-unsafe mode=%s %s\\n' "$(ts)" "$ENV_MODE" "$ENV_FILE" >> "$LOG"
        exit 5
    fi
    . "$ENV_FILE"
fi

# Run topology: the worker resumes in the worktree. Do NOT export CONDUCTOR_RUN_BRANCH — the CLI
# reads .conductor/run_branch (single source of truth); a stale literal here would override it.
export CONDUCTOR_HOME="$WORKTREE"
cd "$WORKTREE" || {{ printf '%s worktree-missing %s\\n' "$(ts)" "$WORKTREE" >> "$LOG"; exit 4; }}
mkdir -p "$PROJECT/.conductor"

# (c) one headless fire at a time — hold the lock in the main checkout for the whole fire.
exec 9>"$PROJECT/.conductor/resume.lock"
flock -n 9 || exit 0

# (a) never double-drive: exit if a claude process already holds the project OR worktree cwd (a
#     live terminal session or a prior fire is then the sole driver).
for pid in $(pgrep -f 'claude' 2>/dev/null); do
    cwd="$(readlink "/proc/$pid/cwd" 2>/dev/null || true)"
    case "$cwd" in
        "$PROJECT"|"$PROJECT"/*|"$WORKTREE"|"$WORKTREE"/*) exit 0 ;;
    esac
done

# (b) finished runs get no-op fires: exit once the spec done-gate is green.
"$CONDUCTOR" assert run --level spec >/dev/null 2>&1 && exit 0

# One headless phase of progress, in the run worktree. Bracket the fire in the log so a stalled
# or crash-looping driver is visible: `fire-start` with no matching `fire-end` = a hung fire
# (e.g. a headless -p session BLOCKED on a permission prompt it cannot answer); `fire-end rc=`
# non-zero = the fire errored out. Reconcile's log-tail warns on either.
#
# PERMISSION OPT-IN (owner decision — NOT defaulted): an autonomous phase runs gh PR create/merge,
# push, docker, broad edits, and subagents. A headless `-p` session can't answer permission
# prompts, so if none of those are pre-authorized it STALLS on the first one — the same
# silent-stall CLASS this driver otherwise fixes. To let unattended fires complete, set in
# resume-env.sh EITHER a least-privilege allowlist (point claude at a scoped settings.json) OR, for
# full autonomy, CONDUCTOR_RESUME_CLAUDE_FLAGS="--dangerously-skip-permissions". The default here
# is EMPTY (supervised only): a full-access agent firing every heartbeat is a standing security
# posture, so the owner opts in explicitly, never the generator.
# Re-parse the owner's flags with THEIR OWN quoting (a bare unquoted expansion would word-split
# a quoted `--settings '/path with space'` into fragments). eval adds no new trust surface here:
# resume-env.sh is already sourced — i.e. executed — owner-owned, 0600-guarded content.
eval "set -- ${{CONDUCTOR_RESUME_CLAUDE_FLAGS:-}}"
# POSTURE VISIBILITY (audit, review A-4/A-6): label every fire with the permission posture
# DERIVED from the SAME parsed argv the fire executes with — never a constant, never the raw
# flag value or a settings path (the log must not leak them), and never a second divergent
# parse (a quoted 'bypassPermissions' value must log what it executes). Bypass wins when both
# appear: the more privileged posture is the honest label. Patterns are space-anchored so a
# flag VALUE merely containing the substring (e.g. a path named x--dangerously-…) cannot
# mislabel the fire; --permission-mode bypassPermissions is the other spelling of full bypass.
POSTURE="supervised"
case " $* " in
    *" --dangerously-skip-permissions"*|*" --permission-mode bypassPermissions"*|*" --permission-mode=bypassPermissions"*) POSTURE="full-bypass" ;;
    *" --settings"*) POSTURE="scoped" ;;
esac
printf '%s fire-start posture=%s\\n' "$(ts)" "$POSTURE" >> "$LOG"
"$CLAUDE_BIN" -p "/conductor:autodev" "$@" >> "$LOG" 2>&1
rc=$?
printf '%s fire-end rc=%s\\n' "$(ts)" "$rc" >> "$LOG"
exit "$rc"
"""


def verify(project: str, worktree: str, script_path: str) -> tuple[bool, list[str]]:
    """Is the installed driver the current template for this run? Returns (ok, reasons). ok=False
    means `/conductor:start` reconcile should regenerate. Non-destructive: only reads."""
    reasons: list[str] = []
    if not os.path.isfile(script_path):
        return False, [f"missing: {script_path}"]
    with open(script_path, encoding="utf-8") as f:
        installed = f.read()
    if _MARKER not in installed:
        reasons.append(
            f"pre-v{TEMPLATE_VERSION} template (no '{_MARKER}') — regenerate"
        )
    for pat, why in _ROT_PATTERNS:
        if pat.search(installed):
            reasons.append(f"rot: {why}")
    # Surface owner/machine env so a regeneration MIGRATES it to resume-env.sh, never drops it.
    inline_env = sorted(set(_OWNER_ENV_RE.findall(installed)))
    if inline_env:
        reasons.append(
            "owner-env inline (move to <project>/.conductor/resume-env.sh before regenerating so "
            "it is not lost): " + ", ".join(inline_env)
        )
    if installed != render(project, worktree):
        reasons.append(
            "differs from current template (stale or hand-edited) — regenerate"
        )
    return (not reasons), reasons


def _write(project: str, worktree: str, out: str | None, force: bool = False) -> int:
    text = render(project, worktree)
    if out is None:
        sys.stdout.write(text)
        return 0
    # No-clobber guard: never overwrite a driver that carries INLINE owner env — the
    # mechanical "verify fails -> write" reconcile path would otherwise silently drop the
    # owner's CONDUCTOR_MERGE_VERIFY etc. Refuse (exit 2) with the exact lines to migrate;
    # --force is the deliberate override once they live in resume-env.sh.
    if os.path.isfile(out) and not force:
        with open(out, encoding="utf-8") as f:
            existing = f.read()
        inline = sorted(set(_OWNER_ENV_RE.findall(existing)))
        if inline:
            print(
                f"refusing to overwrite {out}: it has inline owner env "
                f"({', '.join(inline)}). Move those exports into "
                f"{os.path.dirname(out) or '.'}/resume-env.sh, then re-run with --force.",
                file=sys.stderr,
            )
            return 2
    with open(out, "w", encoding="utf-8") as f:
        f.write(text)
    os.chmod(out, os.stat(out).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"wrote {out} (template v{TEMPLATE_VERSION})", file=sys.stderr)
    # Awareness nudge (owner decision, never auto-enabled): unless the run worktree pre-authorizes
    # every tool an autonomous phase needs, an unattended headless fire STALLS on the first
    # permission prompt. Gate on "permission posture UNDECIDED", not "resume-env.sh absent": a
    # file that exists but sets no posture (empty FLAGS, unrelated exports) still stalls
    # unattended fires, so it still gets the nudge. Point at both opt-ins without choosing.
    env_path = os.path.join(os.path.dirname(out) or ".", "resume-env.sh")
    if not _posture_decided(env_path):
        print(
            f"note: unattended fires need permissions pre-authorized or they STALL on the "
            f"first prompt. Pick a posture in {env_path}:\n"
            f'  (scoped) CONDUCTOR_RESUME_CLAUDE_FLAGS="--settings <path-to-scoped-settings.json>"\n'
            f"           — least privilege: allowlist git/gh/pytest/ruff/pyright/conductor/docker\n"
            f'  (full)   CONDUCTOR_RESUME_CLAUDE_FLAGS="--dangerously-skip-permissions"\n'
            f"           — standing full-access posture; your explicit call, never defaulted.",
            file=sys.stderr,
        )
    return 0


# The posture spellings the DRIVER's fire-start case recognizes — probe and driver must
# agree, or write re-nudges an owner who already decided (training them to ignore it).
_POSTURE_TOKENS = (
    "--dangerously-skip-permissions",
    "--permission-mode bypassPermissions",
    "--permission-mode=bypassPermissions",
    "--settings",
)
_FLAGS_VAR = "CONDUCTOR_RESUME_CLAUDE_FLAGS"


def _posture_decided(env_path: str) -> bool:
    """Has the owner picked a permission posture in resume-env.sh? DECIDED iff an ACTIVE
    CONDUCTOR_RESUME_CLAUDE_FLAGS assignment VALUE carries a bypass or --settings posture.
    Lines are parsed shell-wise (shlex, comments stripped) so a commented-out example line
    or a comment tail on an empty assignment never counts as a decision. Absent/unreadable
    file, malformed line, or a posture-less value is UNDECIDED (nudge fires)."""
    if not os.path.isfile(env_path):
        return False
    try:
        with open(env_path, encoding="utf-8") as f:
            lines = f.read().splitlines()
    except OSError:
        return False
    # Shell semantics: the FINAL effective assignment wins — an early posture followed by a
    # reassignment to "" (or an unset) is undecided at runtime and must still nudge.
    final_value: str | None = None
    for ln in lines:
        try:
            words = shlex.split(ln, comments=True)
        except ValueError:  # unbalanced quotes — malformed, ignore the line
            continue
        for i, word in enumerate(words):
            if word.startswith(f"{_FLAGS_VAR}="):
                final_value = word[len(_FLAGS_VAR) + 1 :]
            elif word == "unset" and _FLAGS_VAR in words[i + 1 :]:
                final_value = None
    if final_value is None:
        return False
    return any(tok in final_value for tok in _POSTURE_TOKENS)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        prog="conductor resume-script",
        description="Generate/verify the Tier-B OS-cron resume driver with run-time bin resolution.",
    )
    sub = p.add_subparsers(dest="cmd", required=True)
    for name in ("write", "verify"):
        sp = sub.add_parser(name)
        sp.add_argument(
            "--worktree", required=True, help="run worktree (CONDUCTOR_HOME)"
        )
        sp.add_argument(
            "--project", required=True, help="owner main-checkout root (lock + log)"
        )
        if name == "write":
            sp.add_argument(
                "--out", default=None, help="write here + chmod +x (default: stdout)"
            )
            sp.add_argument(
                "--force",
                action="store_true",
                help="overwrite even if the target has inline owner env (migrate it first)",
            )
        else:
            sp.add_argument(
                "--script", required=True, help="installed driver to verify"
            )
    args = p.parse_args(argv)
    if args.cmd == "write":
        return _write(args.project, args.worktree, args.out, args.force)
    ok, reasons = verify(args.project, args.worktree, args.script)
    for r in reasons:
        print(r, file=sys.stderr)
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
