"""Generate + verify the Tier-B OS-cron resume driver (`.conductor/resume-autodev.sh`).

Why this is a tested module, not skill prose: the live-run silent-stall of 2026-07-05
(docs/reviews/2026-07-05-conductor-tier-b-driver-robustness.md) traced to prose that told the
agent to "write a resume script that runs `claude -p ...`" without saying HOW to resolve the
bins under cron's minimal PATH. The agent baked in generation-time absolute paths (a
node-version-pinned `claude`, a version-pinned `conductor`); both rotted on the next
claude/plugin upgrade and every headless fire died silently. Making the script mechanical fixes
the root cause: one source of truth, resolved at RUN time, verifiable on reconcile.

Split of concerns the render enforces:
- MECHANICAL (this module owns, regenerable): bin resolution, PATH repair, fail-loud, the three
  guards (no-double-drive, done-gate-green exit, flock), the fire.
- OWNER/MACHINE config (never baked here, sourced from `<project>/.conductor/resume-env.sh` so
  regeneration can never clobber it): `CONDUCTOR_MERGE_VERIFY`, `CONDUCTOR_PLUGIN_DIRS`,
  `DOCKER_HOST`, `CONDUCTOR_RESUME_CLAUDE_FLAGS`.

`CONDUCTOR_RUN_BRANCH` is deliberately NOT exported: a stale literal would override
`.conductor/run_branch` in `merge_gate._expected_base()` and pin an out-of-date branch. The file
is the single source of truth.
"""

from __future__ import annotations

import argparse
import os
import re
import stat
import sys

# Bump when `render` changes so `verify` flags already-installed scripts as stale and
# `/conductor:start` reconcile regenerates them (self-heal on upgrade).
TEMPLATE_VERSION = 2
_MARKER = f"# conductor-resume-template: v{TEMPLATE_VERSION}"

# Antipatterns whose PRESENCE in an installed script means it is a rotted pre-v2 driver: a
# node-version-pinned bin path, or a plugin path pinned to a specific conductor version.
_ROT_PATTERNS = (
    (
        re.compile(r"/versions/v?\d+\.\d+\.\d+/"),
        "version-pinned runtime path (rots on upgrade)",
    ),
    (
        re.compile(r"/conductor/\d+\.\d+\.\d+/bin/conductor"),
        "version-pinned conductor path (rots on upgrade)",
    ),
)
# Owner/machine env an old inline script may carry; verify surfaces these so a regeneration
# migrates them to resume-env.sh instead of silently dropping them.
_OWNER_ENV_RE = re.compile(
    r"^\s*export\s+(CONDUCTOR_MERGE_VERIFY|CONDUCTOR_PLUGIN_DIRS|DOCKER_HOST|CONDUCTOR_RESUME_CLAUDE_FLAGS)\b",
    re.MULTILINE,
)


def render(project: str, worktree: str) -> str:
    """The Tier-B driver script, deterministic in (project, worktree). project = the owner
    main-checkout root (lock + log live there, shared across drivers); worktree = the run
    worktree the worker resumes in (never the owner checkout)."""
    return f"""#!/usr/bin/env bash
{_MARKER}
# conductor Tier-B resume driver — GENERATED by `conductor resume-script write`. Do NOT hand-edit.
#
# OWNER-OWNED run infrastructure: the autodev worker never modifies it. `/conductor:start`
# reconcile regenerates it (via `conductor resume-script verify` -> `write`) when this template
# changes or its bins stop resolving, so a claude/node/plugin upgrade SELF-HEALS instead of
# silently stalling. Machine/run-specific env (CONDUCTOR_MERGE_VERIFY, CONDUCTOR_PLUGIN_DIRS,
# DOCKER_HOST, CONDUCTOR_RESUME_CLAUDE_FLAGS) lives in <project>/.conductor/resume-env.sh — this
# script sources it and never bakes it in, so regeneration can never clobber owner config.
set -u

PROJECT="{project}"
WORKTREE="{worktree}"
LOG="$PROJECT/.conductor/resume-autodev.log"
ts() {{ date -Is 2>/dev/null || date; }}

# Cron gives a minimal PATH — re-add the known install roots BEFORE resolving bins.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin${{PATH:+:$PATH}}"

# Resolve bins at RUN time. NEVER pin generation-time paths: a versioned node path or a
# version-pinned plugin dir rots on the next upgrade and the fire then dies silently.
CLAUDE_BIN="$(command -v claude || true)"
[ -x "$CLAUDE_BIN" ] || CLAUDE_BIN="$HOME/.local/bin/claude"   # claude 2.x standalone launcher (stable, unversioned)
CONDUCTOR="$(command -v conductor || true)"
[ -x "$CONDUCTOR" ] || CONDUCTOR="$(ls -d "$HOME"/.claude/plugins/cache/*/conductor/*/bin/conductor 2>/dev/null | sort -V | tail -1)"

# Fail LOUD if a bin is unresolvable — silence is the real defect; a stalled run must be visible.
if [ ! -x "$CLAUDE_BIN" ] || [ ! -x "${{CONDUCTOR:-}}" ]; then
    printf '%s driver-unresolved claude=%s conductor=%s\\n' "$(ts)" "$CLAUDE_BIN" "${{CONDUCTOR:-}}" >> "$LOG"
    exit 3
fi

# Owner/machine env (merge-verify command, plugin dirs, docker host, extra claude flags). Kept
# OUT of this generated file so regeneration never clobbers it.
[ -f "$PROJECT/.conductor/resume-env.sh" ] && . "$PROJECT/.conductor/resume-env.sh"

# Run topology: the worker resumes in the worktree. Do NOT export CONDUCTOR_RUN_BRANCH — the CLI
# reads .conductor/run_branch (single source of truth); a stale literal here would override it.
export CONDUCTOR_HOME="$WORKTREE"
cd "$WORKTREE" || {{ printf '%s worktree-missing %s\\n' "$(ts)" "$WORKTREE" >> "$LOG"; exit 4; }}
mkdir -p "$PROJECT/.conductor"

# (c) one headless fire at a time — hold the lock in the main checkout for the whole fire.
exec 9>"$PROJECT/.conductor/resume.lock"
flock -n 9 || exit 0

# (a) never double-drive: exit if a claude process already holds the project OR worktree cwd (a
#     live terminal session or a prior fire is then the sole driver).
for pid in $(pgrep -f 'claude' 2>/dev/null); do
    cwd="$(readlink "/proc/$pid/cwd" 2>/dev/null || true)"
    case "$cwd" in
        "$PROJECT"|"$PROJECT"/*|"$WORKTREE"|"$WORKTREE"/*) exit 0 ;;
    esac
done

# (b) finished runs get no-op fires: exit once the spec done-gate is green.
"$CONDUCTOR" assert run --level spec >/dev/null 2>&1 && exit 0

# One headless phase of progress, in the run worktree. Bracket the fire in the log so a stalled
# or crash-looping driver is visible (fire-start with no matching fire-end = a hung fire).
printf '%s fire-start\\n' "$(ts)" >> "$LOG"
"$CLAUDE_BIN" -p "/conductor:autodev" ${{CONDUCTOR_RESUME_CLAUDE_FLAGS:-}} >> "$LOG" 2>&1
rc=$?
printf '%s fire-end rc=%s\\n' "$(ts)" "$rc" >> "$LOG"
exit "$rc"
"""


def verify(project: str, worktree: str, script_path: str) -> tuple[bool, list[str]]:
    """Is the installed driver the current template for this run? Returns (ok, reasons). ok=False
    means `/conductor:start` reconcile should regenerate. Non-destructive: only reads."""
    reasons: list[str] = []
    if not os.path.isfile(script_path):
        return False, [f"missing: {script_path}"]
    with open(script_path, encoding="utf-8") as f:
        installed = f.read()
    if _MARKER not in installed:
        reasons.append(
            f"pre-v{TEMPLATE_VERSION} template (no '{_MARKER}') — regenerate"
        )
    for pat, why in _ROT_PATTERNS:
        if pat.search(installed):
            reasons.append(f"rot: {why}")
    # Surface owner/machine env so a regeneration MIGRATES it to resume-env.sh, never drops it.
    inline_env = sorted(set(_OWNER_ENV_RE.findall(installed)))
    if inline_env:
        reasons.append(
            "owner-env inline (move to <project>/.conductor/resume-env.sh before regenerating so "
            "it is not lost): " + ", ".join(inline_env)
        )
    if installed != render(project, worktree):
        reasons.append(
            "differs from current template (stale or hand-edited) — regenerate"
        )
    return (not reasons), reasons


def _write(project: str, worktree: str, out: str | None) -> int:
    text = render(project, worktree)
    if out is None:
        sys.stdout.write(text)
        return 0
    with open(out, "w", encoding="utf-8") as f:
        f.write(text)
    os.chmod(out, os.stat(out).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"wrote {out} (template v{TEMPLATE_VERSION})", file=sys.stderr)
    return 0


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        prog="conductor resume-script",
        description="Generate/verify the Tier-B OS-cron resume driver with run-time bin resolution.",
    )
    sub = p.add_subparsers(dest="cmd", required=True)
    for name in ("write", "verify"):
        sp = sub.add_parser(name)
        sp.add_argument(
            "--worktree", required=True, help="run worktree (CONDUCTOR_HOME)"
        )
        sp.add_argument(
            "--project", required=True, help="owner main-checkout root (lock + log)"
        )
        if name == "write":
            sp.add_argument(
                "--out", default=None, help="write here + chmod +x (default: stdout)"
            )
        else:
            sp.add_argument(
                "--script", required=True, help="installed driver to verify"
            )
    args = p.parse_args(argv)
    if args.cmd == "write":
        return _write(args.project, args.worktree, args.out)
    ok, reasons = verify(args.project, args.worktree, args.script)
    for r in reasons:
        print(r, file=sys.stderr)
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
